Login = "mathilde"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "Cothority"
Phys = ["server-0.Cothority.SAFER.isi.deterlab.net", "server-1.Cothority.SAFER.isi.deterlab.net", "server-2.Cothority.SAFER.isi.deterlab.net", "server-3.Cothority.SAFER.isi.deterlab.net", "server-4.Cothority.SAFER.isi.deterlab.net", "server-5.Cothority.SAFER.isi.deterlab.net", "server-6.Cothority.SAFER.isi.deterlab.net", "server-7.Cothority.SAFER.isi.deterlab.net", "server-8.Cothority.SAFER.isi.deterlab.net", "server-9.Cothority.SAFER.isi.deterlab.net"]
Virt = ["10.255.0.1", "10.255.0.2", "10.255.0.3", "10.255.0.4", "10.255.0.5", "10.255.0.6", "10.255.0.7", "10.255.0.8", "10.255.0.9", "10.255.0.10"]
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 10
Simulation = "RandSharePVSS"
Hosts = 10
Debug = 2
RunWait = 0
PreScript = ""
